// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

const SUPABASE_URL = "https://jfiojbbrdfgeruborkzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmaW9qYmJyZGZnZXJ1Ym9ya3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMwMjMxNzQsImV4cCI6MjA5ODU5OTE3NH0._xtoznQWRSuaV-GRX0l4ZfIZCoDEmd4BWsOMwtCxALk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  },
});
